import { useCallback } from "react";
import { useNavigate } from "react-router-dom";

const Privacy = () => {
  const navigate = useNavigate();

  const onLogoClick = useCallback(() => {
    navigate("/");
  }, [navigate]);

  return (
    <div className="relative bg-white w-full overflow-hidden flex flex-col items-start justify-start text-left text-base text-[#212121] font-roboto">
      <div className="self-stretch cursor-pointer bg-white h-[70px] flex flex-row py-3.5 px-0 SE:px-[42px] box-border items-center justify-start">
        <img
          className="relative w-[124.88px] h-9 overflow-hidden shrink-0"
          alt=""
          src="/logo_w.svg"
          onClick={onLogoClick}
        />
      </div>
      <div className="self-stretch flex flex-col p-10 SE:p-[80px] items-start justify-start gap-[80px]">
        <p className="m-0 relative text-5xl font-medium">Privacy policy</p>
        <div className="self-stretch flex flex-col items-start justify-start gap-[40px]">
          <p className="m-0 relative font-medium">1. General:</p>
          <p className="m-0 self-stretch relative leading-[30px]">
            <span className="block">
              This document is an electronic record in terms of Information
              Technology Act, 2000 and rules made there under as applicable and
              the amended provisions pertaining to electronic records in various
              statutes as amended by the Information Technology Act, 2000. This
              electronic record is generated by a computer system and does not
              require any physical or digital signatures. This privacy policy
              document (“Privacy Policy”) is published in accordance with the
              provisions of Rule 4 (1) of the Information Technology (Reasonable
              Security Practices and Procedures and Sensitive Personal Data or
              Information) Rules, 2011 which requires the publishing of a
              privacy policy for handling of or dealing in personal information
              including sensitive personal data or information.
            </span>
            <span className="block">
              Thank you for visiting www.myclub100.com and / or the club100
              mobile application (collectively referred to as the "Site").
              club100 is registered as MIHAN ENTERPRISE, a company incorporated
              under Companies Act, 2013 bearing good and services tax number
              (GST) 24BRVPP7588R2Z6 and having its registered office at Plot No.
              23, Harikesh soc, opp. Indian oil petrol pump, Jahangirpura,
              Rander Road, Surat, Gujarat, 395005 ("club100", "we", "us" or
              "our"). We are committed to protecting and respecting the privacy
              of every person who shares information with it or whose
              information it receives. This Privacy Policy ("Privacy Policy")
              applies to the collection, receipt, storage, usage, processing,
              disclosure, transfer and protection ("Utilization") of your
              Personal Information (defined below) when the user of the Site
              ("User" or "you") uses our Site or avails any services offered by
              club100 through the Site.
            </span>
            <span className="block">
              The capitalized terms that are used but not defined in this
              Privacy Policy will have the same meaning as in our Terms and
              Conditions. By using the services or by otherwise giving us your
              information, you will be deemed to have read, understood and
              agreed to the practices and policies outlined in this privacy
              policy and agree to be bound by the privacy policy. You hereby
              consent to our collection, use and sharing, disclosure of your
              information as described in this privacy policy. We reserve the
              right to change, modify, add or delete portions of the terms of
              this privacy policy, at our sole discretion, at any time. If you
              do not agree with this privacy policy at any time, do not use any
              of the services or give us any of your information. If you use the
              services on behalf of someone else (such as your child) or an
              entity (such as your employer), you represent that you are
              authorized by such individual or entity to (I) Accept this privacy
              policy on such individual’s or entity’s behalf, and (II) consent
              on behalf of such individual or entity to our collection, use and
              disclosure of such individual’s or entity’s information as
              described in this privacy policy.
            </span>
          </p>
        </div>
        <div className="self-stretch flex flex-col items-start justify-start gap-[40px]">
          <p className="m-0 relative font-medium">2. Consent:</p>
          <p className="m-0 self-stretch relative leading-[30px] text-[inherit]">
            <span className="block">
              You acknowledge that this Privacy Policy is a part of the User
              Terms of the Site and the other services, by accessing the Site or
              by otherwise providing Us with your Personal Information or by
              making use of the services provided by the Site, You
              unconditionally signify Your (i) assent to the Privacy Policy, and
              (ii) consent to the Utilization of your Personal Information in
              accordance with the provisions of this Privacy Policy.
            </span>
            <span className="block">
              You acknowledge that you are over 18 years of age and are
              providing your Personal Information out of your free will.
            </span>
            <span className="block">
              You have the option not to provide us the Personal Information
              sought to be collected. You will also have an option to withdraw
              your consent at any point, provided such withdrawal of the consent
              is intimated to us in writing at support@myclub100.com. If you do
              not provide us your Personal Information or if you withdraw the
              consent to provide us with your Personal Information at any point
              in time, please note that your withdrawal of consent, may result
              in club100 being unable to provide you with its services or to
              terminate any existing relationship club100 may have with you.
            </span>
            <span className="block">
              {`Our Site is accessible to children under the age of 18. club100 strongly encourages parents and guardians to supervise the online activities of their minor children and consider using parental control tools. These tools also can prevent minors from disclosing their name, address, and other personally identifiable information online without parental permission. Although the Site and services are not intended for use by minors, club100 respects the privacy of minors who may inadvertently use the Site. We do not knowingly collect any Personal Information from children (without the consent of their parents/guardians). Please contact us at `}
              <a
                className="text-[inherit]"
                href="mailto:support@myclub100.com"
                target="_blank"
              >
                <span className="[text-decoration:underline]">
                  support@myclub100.com
                </span>
              </a>{" "}
              , if you are aware that we may have inadvertently collected
              Personal Information from a child, and we will delete that
              information as soon as possible.
            </span>
          </p>
        </div>
        <div className="self-stretch flex flex-col items-start justify-start gap-[40px]">
          <p className="m-0 relative font-medium">3. Grievance Redressal:</p>
          <div className="m-0 self-stretch relative text-[inherit] leading-[30px] font-inherit">
            <span className="block">
              club100 provides multiple channels for you to request for support
              or to communicate any grievances you may have:
            </span>
            <ul className="m-0 list-disc pl-[21px]">
              <li className="mb-0">
                By sending an email to hello@myclub100.com
              </li>
              <li className="mb-0">By Whatsapp on +91 7016580318</li>
            </ul>
            <span className="block">{`Any of your queries & requests shall be responded to within 2 (two) working days of receipt. Resolution, appropriate and to your satisfaction shall be provided as soon as possible depending upon the nature of the request.`}</span>
            <span className="block">
              If you are not satisfied by the resolution provided, you may
              escalate your grievance to the grievance officer through email or
              in writing, whose details are mentioned below:
            </span>
            <span className="block">Name: Nishidh Patel</span>
            <span className="block">Email: grievance@myclub100.com</span>
            <span className="block">
              We request you to please provide the following information in your
              complaint:-
            </span>
            <ul className="m-0 list-decimal pl-[21px]">
              <li className="mb-0">
                Identification of the information provided by you.
              </li>
              <li className="mb-0">
                Clear statement as to whether the information is personal
                information or sensitive personal information.
              </li>
              <li className="mb-0">
                Your address, registered telephone number or e-mail address.
              </li>
              <li className="mb-0">
                A statement that you have a good-faith belief that use of the
                information has been processed incorrectly or disclosed without
                authorization, as the case may be.
              </li>
              <li className="mb-0">
                A statement, under penalty of perjury, that the information in
                the notice is accurate, and that you are authorized to act on
                behalf of the owner of the right that is allegedly infringed.
              </li>
            </ul>
            <span className="block">
              club100 may reach out to you to confirm or discuss certain details
              about your complaint and issues raised.
            </span>
            <span className="block">
              club100 shall not be responsible for any communication, if
              addressed, to any non-designated person in this regard.
            </span>
            <span className="block">
              You may also contact us in case you have any questions /
              suggestions about the Privacy Policy using the contact information
              mentioned above.
            </span>
            <span className="block">
              The Grievance Officer is identified above pursuant to the
              provisions of applicable laws including but not limited to the
              Information Technology Act, 2000 and the Consumer Protection Act,
              2019, and the rules enacted under those laws.
            </span>
          </div>
        </div>
        <div className="self-stretch flex flex-col items-start justify-start gap-[40px]">
          <p className="m-0 relative font-medium">
            4. Personal information collected:
          </p>
          <div className="m-0 self-stretch relative text-[inherit] leading-[30px] font-inherit">
            <span className="block">
              In order to provide services to you we might require you to
              voluntarily provide us certain information that personally
              identifies you. You hereby consent to the collection of such
              information by club100. The information that we may collect from
              you, or about you, may include but are not limited to, the
              following:
            </span>
            <ul className="m-0 list-decimal pl-[21px]">
              <li className="mb-0">Name of the User;</li>
              <li className="mb-0">Birth date/age;</li>
              <li className="mb-0">Gender;</li>
              <li className="mb-0">
                Address (including country and pin/postal code);
              </li>
              <li className="mb-0">
                Financial and KYC information (such as passport, driving
                licence, proof of possession of Aadhaar number, Voter's Identity
                Card issued by the Election Commission of India, job card issued
                by NREGA duly signed by an officer of the State Government, or
                letter issued by the National Population Register containing
                details of name and address); Phone number/mobile number;
              </li>
              <li className="mb-0">Email address;</li>
              <li className="mb-0">
                Records of interaction with club100’s representatives;
              </li>
              <li className="mb-0">
                Your usage details such as time, frequency, duration and pattern
                of use, features used and the amount of storage used;
              </li>
              <li className="mb-0">
                Internet protocol address, browser type, browser language,
                referring URL, files accessed, errors generated, time zone,
                operating system and other visitor details collected in Our log
                files, the pages of our Site that You visit, the time and date
                of Your visit, the time spent on those pages and other
                statistics ("Log Data"); and
              </li>
              <li>
                Any other information that is willingly shared by you.
                (Collectively referred to as "Personal Information").
              </li>
            </ul>
          </div>
        </div>
        <div className="self-stretch flex flex-col items-start justify-start gap-[40px]">
          <p className="m-0 relative font-medium">
            5. How we collect personal information:
          </p>
          <div className="self-stretch relative leading-[30px] font-roboto">
            <p className="m-0">
              The methods by which we collect your Personal Information include
              but are not limited to the following:
            </p>
            <ul className="m-0 list-decimal pl-[21px]">
              <li className="mb-0">
                When you access our Site or use any features of our Site;
              </li>
              <li className="mb-0">
                When you provide your Personal Information to us;
              </li>
              <li className="mb-0">
                During the course of services provided to you by us;
              </li>
              <li className="mb-0">
                Through your computer/device, once you have granted permissions
                to our Site;
              </li>
              <li className="mb-0">Through club100’s representatives;</li>
              <li className="mb-0">
                Through use of cookies (also discussed below); or
              </li>
            </ul>
            <p className="m-0">
              We collect information that your browser/app sends whenever you
              visit our Site, such as the Log Data. In addition, we may use
              third party services to collect, monitor and analyze such Log
              Data. This information is kept completely secure.
            </p>
          </div>
        </div>
        <div className="self-stretch flex flex-col items-start justify-start gap-[40px]">
          <p className="m-0 relative font-medium">
            6. Use of personal information:
          </p>
          <div className="m-0 self-stretch relative text-[inherit] leading-[30px] font-inherit">
            <span className="block">
              We recognize and acknowledge the value and importance of the
              protection of your Personal Information and ensure that the same
              will be used for the intended purpose(s). By virtue of this
              Privacy Policy, We will collect/receive/share/process/use/store
              your Personal Information in accordance with applicable laws to
              provide you with the services, enhance the user experience, manage
              our relationship with You, build user insights, analyze data for
              the introduction of new services and features, and as may be
              required to comply with any regulatory requirements and
              contractual obligations, which may inter alia include:
            </span>
            <ul className="m-0 list-decimal pl-[21px]">
              <li className="mb-0">To provide effective services;</li>
              <li className="mb-0">
                To resolve any customer support related issues;
              </li>
              <li className="mb-0">To operate and improve the Site;</li>
              <li className="mb-0">
                To perform research and analysis for our understanding,
                information, analysis, services and technologies in order to
                provide all users improved quality of care; and ensuring that
                the content and advertising displayed are customized to your
                interests and preferences;
              </li>
              <li className="mb-0">
                To contact you via phone, SMS or email for appointments,
                technical issues, payment reminders, obtaining feedback and
                other security announcements;
              </li>
              <li className="mb-0">
                To send promotional and marketing emails from us or any of our
                channel partners via SMS, email, snail mail or third-party
                communication services such as Mailchimp, Facebook etc.;
              </li>
              <li className="mb-0">
                To advertise products and services of club100 and third parties;
              </li>
              <li className="mb-0">
                To transfer information about you, if we are merged with another
                company;
              </li>
              <li className="mb-0">
                To share with our business partners for provision of specific
                services you have ordered so as to enable them to provide
                effective services to you;
              </li>
              <li className="mb-0">
                To administer or otherwise carry out our obligations in relation
                to any agreement you have with Us;
              </li>
              <li className="mb-0">For purposes of KYC verification;</li>
              <li className="mb-0">
                To build your profile/user account on the Site;
              </li>
              <li>
                To investigate, prevent, or take action regarding illegal
                activities, suspected fraud, violations of our Terms of Use,
                breach of our agreement with you or as otherwise required by
                law. (Collectively referred to as "Purpose(s)").
              </li>
            </ul>
          </div>
        </div>
        <div className="self-stretch flex flex-col items-start justify-start gap-[40px]">
          <p className="m-0 relative font-medium">
            7. Sharing and transferring of personal information:
          </p>
          <ul className="self-stretch relative text-[inherit] leading-[30px] font-inherit">
            <p className="m-0">
              Your Personal Information may be used for various purposes
              including but not limited to the following:
            </p>
            <ul className="m-0 list-decimal pl-[21px]">
              <li className="mb-0">
                We may disclose Personal Information about you to our
                representatives and other third parties to comply with
                applicable laws and regulations. We also reserve the right to
                disclose your Personal Information to third parties in an
                anonymous or aggregate form, to understand customer trends and
                patterns and manage and improve our business relationships. We
                provide your Personal Information to our business partners,
                representatives and third party processors to administer and
                process for the purposes notified to you in this Privacy Policy,
                and we may also share such details with third parties (such as
                auditors or legal advisors) to obtain professional advice. Any
                such processing will be governed by an agreement in the form
                required by law, preserving any and all of your statutory data
                protection rights. You authorize us to exchange, transfer,
                share, part with all or any of your Personal Information, across
                borders and from Your country to any other countries across the
                world with our affiliates/agents/third party service
                providers/partners/banks and financial institutions for the
                Purposes specified under this Privacy Policy or as may be
                required by applicable law.
              </li>
              <li className="mb-0">
                You hereby consent and authorize us to publish feedback obtained
                by you on our Site.
              </li>
              <li className="mb-0">
                User's financial information are transacted upon secure sites of
                approved payment gateways which are digitally under encryption,
                thereby providing the highest possible degree of care as per
                current technology. However, User is advised to exercise
                discretion while saving the payment details.
              </li>
              <li className="mb-0">
                You acknowledge that club100 may be obligated by law to disclose
                or transfer your Personal Information with Courts and Government
                agencies in certain instances such as for verification of
                identity, or for prevention, detection, investigation,
                prosecution, and punishment for offences, or in compliance with
                laws. You hereby consent to disclosure or transfer of your
                Personal Information in these instances.
              </li>
              <li className="mb-0">
                Notwithstanding the above, we are not responsible for the
                confidentiality, security or distribution of Your Personal
                Information by third-parties outside the scope of our agreement
                with such third-parties. Further, We will not be responsible for
                any breach of security or for any actions/omissions of any
                third-parties or events that are beyond the reasonable control
                of us including but not limited to, acts of government, computer
                hacking, unauthorized access to computer data and storage
                device, computer crashes, breach of security and encryption,
                poor quality of Internet service or telephone service of the
                User etc.
              </li>
              <li className="mb-0">
                We may share your Personal Information with our other corporate
                and/or associate entities and affiliates to (i) help detect and
                prevent identity theft, fraud and other potentially illegal acts
                and cyber security incidents, and (ii) help and detect
                co-related/related or multiple accounts to prevent abuse of our
                services.
              </li>
              <li>
                Your KYC will be shared with our partners for purpose of
                verification and transfer of units. By agreeing to terms and
                condition you are hereby authorizing MIHAN ENTERPRISE to share
                the KYC details.
              </li>
            </ul>
          </ul>
        </div>
        <div className="self-stretch flex flex-col items-start justify-start gap-[40px]">
          <p className="m-0 relative font-medium">8. Use of cookies:</p>
          <p className="m-0 self-stretch relative leading-[30px]">
            <span className="block">
              We, our third party service providers and our partners may send
              "cookies" to your computer or use similar technologies to enhance
              your online experience at our Site. "Cookies" are files that can
              identify you as a unique customer and store your personal
              preferences as product preferences to tells us which site pages
              you have visited and in what order. We use cookies and other
              technical information to personalize your visit to the Site, to
              analyze traffic on the Site and to track user trends, patterns and
              selections for authorized download and for technical reasons
              connected with your use of our Site.
            </span>
            <span className="block">
              Cookies can either be permanent (i.e. they remain on your computer
              until you delete them) or temporary (i.e. they last only until you
              close your browser). We may store both temporary and permanent
              ‘cookies’ on your computer/device to store certain data (that is
              not sensitive Personal Information). You can erase or choose to
              block these cookies from your computer. You can configure your
              computer’s browser to alert you when we attempt to send you a
              cookie with an option to accept or refuse the cookie. If you have
              turned cookies off, you may be prevented from using certain
              features of the Site.
            </span>
            <span className="block">
              You are always free to decline our cookies if your device permits,
              although in that case you may not be able to use certain features
              on the Site.
            </span>
            <span className="block">
              We do not control the use of cookies by third parties.
            </span>
          </p>
        </div>
        <div className="self-stretch flex flex-col items-start justify-start gap-[40px]">
          <p className="m-0 relative font-medium">9. Security:</p>
          <p className="m-0 self-stretch relative leading-[30px]">
            <span className="block">
              The security of your Personal Information is important to us. We
              have adopted reasonable security practices and procedures
              including role-based access, secure communication, password
              protection, encryption, etc. to ensure that the Personal
              Information collected is secure.
            </span>
            <span className="block">
              We restrict access to your Personal Information to us and our
              affiliates’ employees, agents, third party service providers,
              partners, and agencies who need to know such Personal Information
              in relation to the Purposes as specified above in this Privacy
              Policy, provided that such entities agree to abide by this Privacy
              Policy.
            </span>
            <span className="block">
              We have also implemented information security practices and
              standards and have in place information security programs and
              policies containing managerial, technical, operational and
              physical security measures that are in compliance with the
              applicable laws including, so as to protect the information
              provided to us from unauthorized access, use, modification,
              damage, disclosure or impairment. Further, we may from time to
              time use reasonable additional or alternative procedures to ensure
              the security and confidentiality of Your Personal Information
              through our Investment Platform.
            </span>
            <span className="block">
              While we will endeavor to take all reasonable and appropriate
              steps to keep secure any information which we hold about you and
              prevent unauthorized access, you acknowledge that the internet is
              not 100% secure. No data transmission over the internet is fully
              secure, so we cannot ensure or warrant the security of any
              information you submit to us. Further, we do not guarantee in any
              way, the security of any information that you transmit or share on
              the Site; and you do so at your own risk.
            </span>
            <span className="block">
              If you think that the security of your account has been
              compromised, change your password and contact us immediately.
            </span>
          </p>
        </div>
        <div className="self-stretch flex flex-col items-start justify-start gap-[40px]">
          <p className="m-0 relative font-medium">10. Third party links:</p>
          <p className="m-0 self-stretch relative leading-[30px]">
            During your interactions with us, it may happen that we
            provide/include links and hyperlinks of third-party websites not
            owned or managed by us (“Third-party Sites”). It may also happen
            that you or other Users may include links and hyperlinks of
            third-party Sites. The listing of such third-party websites (by you,
            other Users or by us) does not imply endorsement of such third-party
            websites by club100. Such third-party websites are governed by their
            own terms and conditions and when you access such Third-party Sites,
            you will be governed by the terms of such third-party websites. You
            must use your own discretion while accessing or using third-party
            websites. We do not make any representations regarding the
            availability and performance of any of the third-party websites. We
            are not responsible for the content, terms of use, privacy policies
            and practices of such third-party websites. We do not bear any
            liability arising out of your use of third-party websites.
          </p>
        </div>
        <div className="self-stretch flex flex-col items-start justify-start gap-[40px]">
          <p className="m-0 relative font-medium">11. Access:</p>
          <p className="m-0 self-stretch relative leading-[30px]">
            If you need to update your Personal Information or have any
            grievance with respect to the processing or use of your Personal
            Information, or request that we no longer use your Personal
            Information to provide you services, or opt-out of receiving
            communications such as promotional and marketing-related information
            regarding the services, for any reason, You may send Us an email at
            support@myclub100.com and we will take all reasonable efforts to
            incorporate the changes within a reasonable period of time.
          </p>
        </div>
        <div className="self-stretch flex flex-col items-start justify-start gap-[40px]">
          <p className="m-0 relative font-medium">12. Compliance with law:</p>
          <div className="self-stretch relative text-[inherit] leading-[30px] font-inherit">
            <p className="m-0">
              The contents of this Privacy Policy are governed by the laws of
              India. You are not allowed to use the services of the Site if any
              of the terms of this Privacy Policy are not in accordance with the
              applicable laws of your country.
            </p>
            <p className="m-0">
              Some of our Services allow you to upload, submit, store, send or
              receive content. When you upload, submit, store, publish, send or
              receive content to or through our Services, you provide us with
              your consent to utilize such content, including for our marketing
              purposes, subject to our Privacy Policy.
            </p>
            <p className="m-0">Such content must not:</p>
            <ul className="m-0 list-decimal pl-[21px]">
              <li className="mb-0">
                Be harmful, harassing, blasphemous, defamatory, obscene,
                pornographic, pedophilic, libelous, invasive of another’s
                privacy, hateful or racially or ethnically objectionable,
                disparaging, and relating to, or encouraging money laundering or
                gambling.
              </li>
              <li className="mb-0">Harm minors in any way.</li>
              <li className="mb-0">
                Infringe any patent, trademark, copyright or other intellectual
                property rights.
              </li>
              <li className="mb-0">
                Deceive or mislead the reader about the origin of such messages
                or communicate any information that is grossly offensive or
                menacing in nature.
              </li>
              <li className="mb-0">
                Contain software viruses or any other programs designed to
                interrupt, destroy or limit the functionality of another
                computer or mobile device.
              </li>
              <li className="mb-0">
                Threaten the unity, integrity, defense, security or sovereignty
                of India, friendly relations with foreign states, or public
                order.
              </li>
              <li className="mb-0">
                Cause the incitement to commit any offence or prevent the
                investigation of any offence.
              </li>
              <li className="mb-0">Be insulting to any other nation.</li>
              <li className="mb-0">Impersonate another person.</li>
              <li>
                Violate the provisions of the Information Technology Act, 2000
                and rules and regulations thereunder or any other applicable
                laws.
              </li>
            </ul>
          </div>
        </div>
        <div className="self-stretch flex flex-col items-start justify-start gap-[40px]">
          <p className="m-0 relative font-medium">
            13. Term of storage of personal information:
          </p>
          <div className="self-stretch relative text-[inherit] leading-[30px] font-inherit">
            <ul className="m-0 list-decimal pl-[21px]">
              <li className="mb-0">
                club100 may keep records of communications, including phone
                calls received and made for making enquiries, orders, feedback
                or other purposes for rendering services effectively and
                efficiently. club100 will be the exclusive owner of such data
                and records. However, all records are regarded as confidential.
                Therefore, will not be divulged to any third party, unless
                required by law.
              </li>
              <li className="mb-0">
                club100 will store your Personal Information at least for a
                reasonable from the last date of use of the services, Site or
                for such period as may be required by law.
              </li>
              <li>
                You are responsible for maintaining the accuracy of the
                information you submit to us, such as your contact information
                provided as part of account registration. If your personal
                information changes, you may correct, delete inaccuracies, or
                amend information by making the change on our member information
                page or by contacting us through support@myclub100.com. We will
                make good faith efforts to make requested changes in our then
                active databases as soon as reasonably practicable. If you
                provide any information that is untrue, inaccurate, out of date
                or incomplete (or becomes untrue, inaccurate, out of date or
                incomplete), or club100 has reasonable grounds to suspect that
                the information provided by you is untrue, inaccurate, out of
                date or incomplete, club100 may, at its sole discretion,
                discontinue the provision of the services to you. There may be
                circumstances where club100 will not correct, delete or update
                your Personal Information, including (a) where the Personal
                Information is opinion data that is kept solely for evaluative
                purpose; and (b) the Personal Information is in documents
                related to a prosecution if all proceedings relating to the
                prosecution have not been completed.
              </li>
            </ul>
          </div>
        </div>
        <div className="self-stretch flex flex-col items-start justify-start gap-[40px]">
          <p className="m-0 relative font-medium">
            14. Changes to the privacy policy:
          </p>
          <div className="self-stretch relative text-[inherit] leading-[30px] font-inherit">
            <ul className="m-0 pl-[21px]">
              <li className="mb-0">
                We reserve the right to update (change, modify, add and/or
                delete) the terms of this Privacy Policy from time to time, at
                our sole discretion, to reflect company initiatives, changes in
                the law or technology or changes in our practices regarding the
                collection and use of Personal Information.
              </li>
              <li>
                When we update our Privacy Policy, we will intimate you of the
                amendments on your email address registered with us or on the
                Site. If you do not agree to the amendments, please do not use
                the Site or services any further. By continuing to use the Site,
                you will be deemed to have consented to the latest version of
                the Privacy Policy.
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Privacy;
