import { useCallback } from "react";
import { useNavigate } from "react-router-dom";

const TermsConditions = () => {
  const navigate = useNavigate();

  const onLogoClick = useCallback(() => {
    navigate("/");
  }, [navigate]);

  return (
    <div className="relative bg-white w-full overflow-hidden flex flex-col items-center justify-start text-left text-base text-[#212121] font-roboto">
      <div className="self-stretch cursor-pointer bg-white h-[70px] flex flex-row py-3.5 px-0 SE:px-[42px] box-border items-center justify-start">
        <img
          className="relative w-[120px] h-12 overflow-hidden shrink-0"
          alt=""
          src="/logo_w.svg"
          onClick={onLogoClick}
        />
      </div>
      <div className="self-stretch flex flex-col p-10 SE:p-[80px] items-start justify-start gap-[80px]">
        <p className="m-0 relative text-5xl font-medium">{`Terms & conditions `}</p>
        <div className="self-stretch flex flex-col items-start justify-center gap-[40px]">
          <p className="m-0 relative font-medium">1. General:</p>
          <p className="m-0 self-stretch relative leading-[30px]">
            <span className="block">
              This document is an electronic record in terms of Information
              Technology Act, 2000 and rules made there under as applicable and
              the amended provisions pertaining to electronic records in various
              statutes as amended by the Information Technology Act, 2000. This
              electronic record is generated by a computer system and does not
              require any physical or digital signatures. This document is
              published in accordance with the provisions of Rule 3(1) of the
              Information Technology (Intermediaries Guidelines) Rules, 2011
              that require publishing the rules and regulations, privacy policy
              and user agreement for access or usage of our website 'www.
              myclub100.com' (hereinafter referred to as the "Website") and / or
              our mobile application for the use of our services (hereinafter
              referred to as the “App”). The Website and the App are hereinafter
              collectively referred to as the “Site”. The Site is an
              internet-based asset ownership portal providing technology
              solutions for access to various financial products and alternative
              investment opportunities (“Services”), owned and operated by MIHAN
              ENTERPRISE , a company incorporated under Companies Act, 2013
              bearing corporate identification number (GST) 24BRVPP7588R2Z6 and
              having its corporate office at 1st Floor, No. 141 Krishnam Arcade,
              Olpad, Surat, Gujrat, 395005, India (hereinafter, referred to as
              "we", "us", "our" and "club100").
            </span>
            <span className="block">
              For the purpose of these User Terms (defined hereinafter), "you",
              "your" or “User” refers to any natural or legal person (whether a
              registered user or otherwise) who accesses the Site, its contents
              and uses the Services offered by club100 on or through the Site.
            </span>
          </p>
        </div>
        <div className="self-stretch flex flex-col items-start justify-start gap-[40px]">
          <p className="m-0 relative font-medium">2. Use of site:</p>
          <p className="m-0 self-stretch relative leading-[30px]">
            <span className="block">
              Your use of our Site and its related sites, Services and tools is
              governed by the terms and conditions as contained in this
              agreement applicable to the Site (“User Terms”). By using the
              Website, you have impliedly agreed and accepted these User Terms.
              If you do not agree or are not willing to be bound by the terms
              and conditions of these User Terms (and the rules and policies
              displayed on the Website), please do not click on the "Accept"
              button and do not seek to obtain access to or otherwise use the
              Website. As long as you comply with the provisions of these User
              Terms, we grant you a personal, non-exclusive, non-transferable,
              limited privilege to enter and use the Website. If you do not
              agree to these User Terms, you agree that your sole and exclusive
              remedy is to discontinue using the Website. Your compliance with
              these User Terms is a condition to your right to access the
              Website. Your breach of any provision of these User Terms will
              automatically, without the requirement of notice or other action,
              revoke and terminate your right to access the Website.
            </span>
            <span className="block">
              It is clarified that the Privacy Policy, and disclaimers form an
              integral part of these User Terms and should be read
              contemporaneously with the User Terms. Illegality or
              unenforceability of one or more provisions of these User Terms
              shall not affect the legality and enforceability of the other
              terms of the User Terms. For avoidance of doubt, if any of the
              provisions becomes void or unenforceable, the rest of the
              provisions of these User Terms shall be binding upon the User.
            </span>
          </p>
        </div>
        <div className="self-stretch flex flex-col items-start justify-start gap-[40px]">
          <p className="m-0 relative font-medium">
            3. Registration on the site:
          </p>
          <p className="m-0 self-stretch relative leading-[30px]">
            <span className="block">
              You must be at least 18 (eighteen) years of age or older (in case
              you are an individual), have a sound mind and not debarred by any
              law to contract in order to access and use the Website. If you use
              the Site or the Services on behalf of someone else (including but
              not limited to, as a legal representative of another individual or
              an entity, you must be authorized by such individual or entity.
              Our Website is accessible to children under the age of 18
              (eighteen), however club100 strongly encourages parents and
              guardians to supervise the online activities of their minor
              children and consider using parental control tools. These tools
              also can prevent minors from disclosing their name, address, and
              other personally identifiable information online without parental
              permission.
            </span>
            <span className="block">
              The Website and the offerings therein are intended only for
              registered Users who have completed the registration process and
              completed the KYC (Know-Your-Customer) requirements set out on the
              Website. A User must agree to become a member of the Website by
              providing ‘Registration Data’ (as set out on the Website) while
              registering on the Website and accept these User Terms. Upon
              ‘Acceptance’, these User Terms will be effective and binding upon
              you along with any amendments made by us at its sole discretion
              and posted on the Website and you will not claim invalidity of
              these User Terms merely on the grounds that these are being
              concluded electronically. For the aforesaid purposes, 'Acceptance'
              will mean your affirmative action in having clicked on the
              "Accept" button as provided on the registration page or any act
              which reflects your use of the Website or the Services provided by
              the Website or any such other actions that implies your
              acceptance.
            </span>
            <span className="block">
              Upon completion of the registration process, the User will be
              allocated a unique identification username (“User ID”) to become
              Registered User and the User may be required to enter either (i) a
              password set by you for your User ID; and / or (ii) a unique
              one-time password (“OTP”) issued by club100 to the User for
              authentication of your User ID each time he/she/it intend(s) to
              use the Website (together “Login Credentials”). You are solely
              responsible for the security of your Login Credentials and You
              will be responsible for all activities that occur under your User
              ID or account. club100 will consider all instructions placed with
              the use of your Login Credentials to have originated from you and
              will not be liable to any person for any loss or damage which may
              arise as a result of any failure by the User to protect their
              Login Credentials. You undertake to immediately notify club100 of
              any unauthorized use of your account or any other breach of
              security. You undertake to not sell or otherwise transfer your
              account/ User ID, or allow any third party to use or access your
              user account. club100 reserves the right to refuse service,
              terminate accounts, or remove or edit content in its sole
              discretion.
            </span>
            <span className="block">
              You confirm and acknowledge that by registering on the Website,
              you authorize and consent to club100 sending promotional and
              marketing content to you through emails, phone calls, short
              message service or other electronic and non-electronic mode of
              communication, and no such communication shall be deemed to be in
              violation of law relating to unsolicited commercial communication.
            </span>
            <span className="block">
              By using this Website, the User authorizes club100 to fetch data
              about the investments made on the platform from the
              counter-parties like Trustees, RTAs, Issuers, etc. By such
              authorization, club100 will have the right to receive data from
              such counter-parties and disseminate the same to the User through
              its Site or platform. Such data shall be held confidential by the
              User and shall be used only for his/her own decision making. The
              data so shared does not represent solicitation of an offer to buy
              or sell any assets or securities.
            </span>
            <span className="block">
              Please be aware that club100 reserves the right to revoke your
              access to the club100 Site, subject to our reasonable discretion.
              In this regard, we may also choose to suspend your account or your
              access to the same as a registered User, in such an event, you may
              contact our support team to assist you/resolve the situation.
            </span>
          </p>
        </div>
        <div className="self-stretch flex flex-col items-start justify-start gap-[40px]">
          <p className="m-0 relative font-medium">
            4. User rights on the site:
          </p>
          <p className="m-0 self-stretch relative leading-[30px]">
            These User Terms govern your access and use of the Website, which
            includes any images, text, illustrations, designs, icons,
            photographs, programs, music clips, downloads, systems and methods
            of trading, video clips, graphics, user interfaces, visual
            interfaces, information, data, tools, products, written materials,
            services and other content (together, "Content"), including but not
            limited to the design, structure, selection, coordination,
            expression and arrangement of the Content available on or through
            the Website. club100 grants you a limited right to use the Website.
            The User will not use the Website in any way that is fraudulent or
            unlawful. Your right to use the Website is subject to your agreement
            to abide by these User Terms in their entirety, as well as any other
            rules, procedures, policies, terms or conditions that govern all or
            any portion of the Website. At any time and for any reason club100
            may revoke your right to use all or any portion of the Website. The
            Website and the Content is not intended for distribution to, or use
            by, any person or entity in any jurisdiction or country outside
            India.
          </p>
        </div>
        <div className="self-stretch flex flex-col items-start justify-start gap-[40px]">
          <p className="m-0 relative font-medium">5. Site security:</p>
          <p className="m-0 self-stretch relative leading-[30px]">
            <span className="block">
              You may not violate or attempt to violate the security of the
              Website. Tampering with any portion of the Website, providing
              untruthful or inaccurate information, misrepresenting your
              identity, or conducting fraudulent activities on the Website,
              whether or not through the use of agents, are prohibited and
              constitute a breach of these User Terms. You are prohibited from
              violating or attempting to violate the security of the Website.
            </span>
            <span className="block">
              You agree to, amongst others, not to (a) license, sell, rent,
              lease, transfer, assign, distribute, host, or otherwise
              commercially exploit the Website; (b) access the Website in order
              to build a similar or competitive service; (c) copy, reproduce,
              distribute, republish, download, displayed, poste or transmit in
              any form or by any means, any Content of the Website (d) use the
              Website in any way that causes, or may cause, damage to the
              club100, the Website, its Users or impair the availability or
              accessibility of the Website in any way which is unlawful,
              illegal, fraudulent or harmful, or in connection with any
              unlawful, illegal, fraudulent or harmful purpose or activity; (e)
              abuse, harass, impersonate, intimidate or threaten other Users;
              (f) post or transmit, or cause to be posted or transmitted, any
              content that is harmful, infringing, libellous, defamatory,
              abusive, offensive, obscene, pornographic, paedophilic, invasive
              of another's privacy, hateful, or racially, ethnically
              objectionable, disparaging, relating or encouraging money
              laundering or otherwise violates any applicable law or right of
              any third party; or that threatens the unity, integrity, defence,
              security or sovereignty of India, friendly relations with foreign
              states, or public order or causes incitement to the commission of
              any cognizable offence or prevents investigation of any offence or
              is insulting any other nations; (g) use the Website for any
              unauthorized purpose, or in violation of any applicable law or
              these User Terms; (h) post or transmit, or cause to be posted or
              transmitted, any communication or solicitation designed or
              intended to obtain access to another User’s account, or private
              information from any User; (i) infringe upon the IP Rights of
              club100 or any third party; (j) submit comments linking to
              affiliate programs, multi-level marketing schemes, sites
              repurposing existing stories or off-topic content; (k) post,
              email, transmit, upload, or otherwise make available any material
              that contains software viruses or any other computer code, trojan
              horse or other code with malicious, disruptive and/or destructive
              features, files or programs designed or functioning to interrupt,
              destroy, or limit the functionality of any computer software or
              hardware or telecommunications equipment, including the Website;
              (l) use any robot, spider, scraper, sniping software or other
              automated means to access the Website for any purpose; (m) conduct
              any systematic or automated data collection activities on or in
              relation to the Website (n) use the Website or any Content any
              part of it to transmit or send unsolicited commercial
              communications, or for any other purposes related to marketing;
              (o) reverse engineer, frame, modify, copy, distribute, transmit,
              display, perform, reproduce, publish, license, create derivative
              works from, transfer, or sell any information, software obtained
              from or part of the Website; (p) disable, remove, defeat, or
              avoiding any security device or system, including, without
              limitation, any login functionality used to authenticate Users;
              (q) attempt to probe, scan or test the vulnerability of a system
              or network or to breach security or authentication measures
              without proper authorization; (r) attempt to interfere with
              service to any user, host or network, including, without
              limitation, via means of submitting a virus to the Website,
              overloading, "flooding," "spamming," "mailbombing" or "crashing;"
              (s) remove any notices, warnings, labels, annotations or
              instructions from any portion of the Website or any related
              material, including, without limitation, any patent, trademark,
              copyright, or other proprietary notices or license provisions; or
              (t) otherwise invading the privacy of, obtaining the identity of,
              or obtaining any personal information about any user of the
              Website. Any violations of system or network security including
              attempts to intentionally access a computer without authorization
              or exceed your authorized access level may result in civil and
              criminal charges, including but not limited to charges under
              applicable laws. club100 may investigate occurrences that might
              involve such violations and may involve, and cooperate with, law
              enforcement authorities in prosecuting users who are involved in
              such violations. We may, without prior notice or warning of any
              kind, restrict or terminate the access of any and all users to the
              Website if we reasonably conclude that such restriction or
              termination is necessary to prevent, or prevent the further
              spread, of a virus, security breach or system malfunction.
            </span>
            <span className="block">
              The Website may contain certain links. Activating links on the
              Website may cause the User to leave the Website. Such links are
              provided solely for Users’ convenience and information. club100
              has not reviewed any of the websites linked with or connected to
              the Website and using links on or to the Website is at each
              individual user’s own risk
            </span>
          </p>
        </div>
        <div className="self-stretch flex flex-col items-start justify-start gap-[40px]">
          <p className="m-0 relative font-medium">6. Third party content:</p>
          <p className="m-0 self-stretch relative leading-[30px]">
            The Site makes available general third party information such as,
            product and service catalogues, advertisements including videos,
            images and photographs of various products and/or services and other
            data from external third party sources including web-site links
            ("Third Party Content"). The provision of Third-Party Content is for
            general informational or advertisement purposes only. You
            acknowledge that the Third-Party Content provided to You is obtained
            from sources believed to be reliable. club100 does not provide any
            guarantee with respect to any Third-Party Content and club100 shall
            not be held liable for any loss suffered by you based on Your
            reliance on or use of such data.
          </p>
        </div>
        <div className="self-stretch flex flex-col items-start justify-start gap-[40px]">
          <p className="m-0 relative font-medium">7. Taxes:</p>
          <p className="m-0 self-stretch relative leading-[30px]">
            <span className="block">
              The User shall be responsible for identifying and paying all
              taxes, duties, cess and other fees and charges (and any penalties,
              interest, and other additions thereto) that are payable by the
              User with respect to the transactions through the Platform.
            </span>
            <span className="block">
              club100 will not be liable to pay any taxes which are payable by
              the User to any governmental authority for any such transaction.
            </span>
          </p>
        </div>
        <div className="self-stretch flex flex-col items-start justify-start gap-[40px]">
          <p className="m-0 relative font-medium">
            8. Use of Google Analytics:
          </p>
          <p className="m-0 self-stretch relative leading-[30px]">
            <span className="block">
              club100 uses Google Analytics, a web analytics service provided by
              Google, Inc. Google Analytics uses first-party cookies to report
              on user interactions with our web-based services. These cookies
              store non-personally identifiable information. Google Analytics
              aggregates technical data (non personally identifiable data
              relating to your usage of our website) with data collected from
              other users. club100 uses this information to identify the most
              popular areas of the Services and how to best present and
              customize them.
            </span>
            <span className="block">
              For more information about how Google handles technical
              information, please visit the site, "How Google uses data when you
              use our partners’ sites or apps", (located
              at:www.google.com/policies/privacy/partners). Under no
              circumstances will your email, password, any personal financial
              data be collected by or shared with Google Analytics.
            </span>
          </p>
        </div>
        <div className="self-stretch flex flex-col items-start justify-start gap-[40px]">
          <p className="m-0 relative font-medium">
            9. Ownership of materials on site:
          </p>
          <p className="m-0 self-stretch relative leading-[30px]">
            You may download or copy Content only to the extent such download is
            expressly permitted in writing on the Website. No right, title or
            interest in any downloaded materials or software is transferred to
            you as a result of any such downloading or copying. You may not
            reproduce (except as noted above), publish, transmit, distribute,
            display, modify, create derivative works from, sell or participate
            in any sale of or exploit in any way, in whole or in part, any of
            the Content, the Website or any related software. Nothing on the
            Website will be interpreted as granting any license or right to use
            any image, trademark, trade dress, logo or service mark on the
            Website. Anything transmitted to the Website by you becomes
            club100’s property and may be used by us for any lawful purpose.
            club100 reserves all rights with respect to copyright and trademark
            ownership of all material on the Website, and will enforce such
            rights to the full extent of the law. Unless otherwise noted, all
            Contents are copyrights, trademarks, trade dress and/or other
            intellectual property owned, controlled or licensed by club100 or by
            third parties who have licensed their materials to club100 and are
            protected by Indian and international copyright laws. The
            compilation of all Contents on the Website is the exclusive property
            of club100 and is also protected by Indian and international
            copyright laws. The Website, including all Information, is owned by
            or licensed to club100 and is subject to and protected by various
            intellectual property rights, including but not limited to
            copyright, trade secrets, trademarks, service marks, brand names and
            other proprietary rights whether under contract, statute or any
            similar provisions (“IP Rights”). All IP Rights are and will remain
            the exclusive property of club100, its respective third-party
            licensors or third parties to whom it is attributed and in using the
            Website individual users will not obtain any rights, title or other
            interest in or to any information on the Website or related IP
            Rights. Subject to the above, individual users are entitled to view
            the Information on the Website and to copy and print such
            information for personal use. Individual users are not permitted to
            sell or distribute or otherwise deal with the Information on the
            Website or any deviations of such information without the prior
            written consent of club100. The Website uses different web analytics
            services and is compliant with their terms and conditions.
          </p>
        </div>
        <div className="self-stretch flex flex-col items-start justify-start gap-[40px]">
          <p className="m-0 relative font-medium">10. No offers or reliance:</p>
          <p className="m-0 self-stretch relative leading-[30px]">
            The Website has been prepared solely for purposes of information.
            The information available on the Website is for convenience of
            presentation and under no circumstances should the Website be used
            or considered as an offer to sell or the invitation or solicitation
            of an offer to buy any asset listed on the Website. Before making a
            decision with respect to purchasing any asset, Users are advised to
            carefully read the related final documentation. Further, club100
            does not give or offer any business advice, investment advice, tax
            or legal advice to anyone using this Website. Accordingly, Users are
            advised to consult with their tax, legal and financial advisors and
            carry out their own due diligence with respect to purchasing any
            asset. Nothing contained on the Website must be relied upon as a
            promise or representation as to past or future performance. The
            Website may contain forward-looking statements. In some cases, you
            can identify forward-looking statements by terminology such as
            "may," "will," "should," "expects," "plans," "anticipates,"
            "believes," "targeted," "projected," "underwritten," "estimates,"
            "predicts," "potential," or "continue" or the negative of these
            terms or other comparable terminology. These forward-looking
            statements include, but are not limited to, statements concerning
            the company, property, risk factors, plans and projections.
            Forward-looking statements are subject to various risks and
            uncertainties. Accordingly, there are or will be important factors
            that could cause actual outcomes or results to differ materially
            from those indicated in these statements. None of club100, the
            issuer nor any other person or entity assumes responsibility for the
            accuracy and completeness of forward-looking statements. Users
            should conduct their own due diligence and not rely on the financial
            assumptions or estimates that are displayed on the Website. Assets
            displayed on the Website are not bank deposits, are not insured and
            are not guaranteed by club100, and may lose value.
          </p>
        </div>
        <div className="self-stretch flex flex-col items-start justify-start gap-[40px]">
          <p className="m-0 relative font-medium">
            11. No warranty; Limitation on liability:
          </p>
          <div className="m-0 self-stretch relative text-[inherit] leading-[30px] font-inherit">
            <span className="block">
              You will not dispute and /or hold club100 responsible for:
            </span>
            <ul className="m-0 px-4 list-disc pl-[21px]">
              <li className="mb-0">
                Any act that is not an obligation of club100 in this Agreement.
              </li>
              <li className="mb-0">
                Any disclosures made by club100 to any statutory body under any
                law.
              </li>
              <li className="mb-0">
                Any loss, notional or otherwise, incurred because of:
              </li>
              <li className="mb-0">
                Delays either at the end of the bank, the Registrar and Transfer
                Agency’s, depositories or any other service providers of
                club100, by no fault of club100;
              </li>
              <li className="mb-0">
                Providing access to information and/or processing of
                instructions authenticated by your Login Credentials;
              </li>
              <li className="mb-0">
                Non-availability or non-accessibility of the website, mobile
                application, electronic payment gateway, telephone(s), or
                office(s) of club100 for reasons including those beyond
                club100’s control;
              </li>
              <li className="mb-0">
                Any penalties, loss or damage to you which is due to the
                negligence or actions of any Service Partner of club100 and not
                caused by any action of club100;
              </li>
              <li className="mb-0">{`Any inaccuracy or typographical error on our website or the mobile application or any written, E-mail & SMS communication. club100 specifically disclaims any liability for such inaccuracies or errors;`}</li>
              <li className="mb-0">
                Any act, omission or delay attributed to you or any Service
                Partners resulting in club100 not being able to provide the
                Services to you.
              </li>
            </ul>
            <span className="block">&nbsp;</span>
            <ul className="block list-decimal">
              <li>
                {" "}
                By using the site, you expressly agree that such use is at your
                sole risk. The site and related services are provided on an "as
                is", "as available" and "with all faults" basis. Neither club100
                nor any of its respective officers, directors, employees,
                agents, third-party content providers, designers, contractors,
                distributors, merchants, sponsors, licensors or the like
                (collectively, "associates") warrant that use of the site or
                related services will be uninterrupted or error-free. Neither
                club100 nor its associates warrant the accuracy, integrity,
                completeness, availability or timeliness of the content provided
                in the site or the materials or services offered in the site now
                or in the future. club100 and its associates specifically
                disclaim all warranties, whether expressed or implied, including
                but not limited to warranties of title, merchantability, fitness
                for a particular purpose or non-infringement of the site,
                information on the site or the results obtained from use of the
                site or related services. club100 and its associates accepts no
                responsibility for updating any party of the site or the content
                therein.
              </li>

              <span className="block list-decimal"></span>

              <li>
                Under no circumstances will club100 or its associates be liable
                to you or anyone else for any direct, consequential, incidental,
                special, exemplary, punitive or other indirect damages,
                including but not limited to lost profits, trading losses,
                unauthorized access, systems failure, communications line
                failure, internet failure or damages that result from use or
                loss of use of the site, content, inconvenience or delay. This
                is true even if club100 has been advised of the possibility of
                such damages or losses.
              </li>
            </ul>
          </div>
        </div>
        <div className="self-stretch flex flex-col items-start justify-start gap-[40px]">
          <p className="m-0 relative font-medium">12. Disclaimer:</p>
          <div className="m-0 self-stretch relative text-[inherit] leading-[30px] font-inherit">
            <ul className="m-0 list-decimal pl-[21px]">
              <li className="mb-0">
                You understand and acknowledge that purchase of the assets
                listed on the Website is speculative in nature and involves a
                high degree of risk, including the risk of loss of capital, and
                is not guaranteed. The Website is suitable only for
                sophisticated investors who fully understand and are capable of
                bearing the risks of purchasing such assets. A User should only
                purchase assets if he/she is able to withstand a total loss of
                capital. No guarantee or representation is made by us that you
                will achieve your investment objectives or will receive a return
                of your capital. The buyers of the assets/securities available
                of the platform should be aware that such assets/securities are
                illiquid in nature and there is no guarantee that they may be
                able to sell/redeem such assets/securities, with or without
                capital depreciation. club100 does not promise to process any
                withdrawal requests, or provide any avenues to liquidate such
                holdings, and the asset will be locked in till maturity. club100
                does not endorse or promote any of the opportunities that appear
                on this Website nor make any recommendations regarding same to
                any User. Users must not construe anything on the Website as
                investment, business, legal or tax advice and the content
                contained herein does not constitute an offer by club100 to
                sell, solicit or make an offer to buy an investment interest.
                Any information made available from our Website, does not
                represent a solicitation of an offer to buy or sell any
                property.
              </li>
              <li>
                Any blogs, content including FAQs and information available on
                club100, available on the Site is merely for educational
                purposes and to disseminate general information about the
                product(s)/service(s) offered through the Site. Nothing
                contained in the blog(s), content(s) available on the website
                are to be construed as legal opinion or investment advice.
                Neither club100 nor the entity(ies), person(s) associated to it
                makes any representations, warranties, or guaranties whatsoever
                as to the blog(s), content(s) available on Site wholly or in
                part, including that of the accuracy or completeness of the
                information provided therein. In no event shall the club100 and/
                or its associated entity(ies), person(s) be liable for any
                direct, indirect, punitive, incidental, special or consequential
                damages which may arise as a result of a person acting upon or
                using the statements, information, ideas, opinions made in the
                blogs and content including FAQs available on the website.
              </li>
            </ul>
          </div>
        </div>
        <div className="self-stretch flex flex-col items-start justify-start gap-[40px]">
          <p className="m-0 relative font-medium">
            13. Representations and Warranties:
          </p>
          <div className="m-0 self-stretch relative text-[inherit] leading-[30px] font-inherit">
            <ul className="m-0 list-decimal pl-[21px]">
              <li className="mb-0">
                By Using this Website, you represent and warrant that:
              </li>
              <li className="mb-0">
                You are a citizen of India or, in case of juridical persons, are
                formed under the applicable laws of India;
              </li>
              <li className="mb-0">
                You are 18 years of age or older and that your use of the
                Website will not violate any applicable law or regulation;
              </li>
              <li className="mb-0">
                During registration as a User on the Website, you have provided
                information, which is true, accurate, current, complete and
                updated about yourself; and
              </li>
              <li className="mb-0">
                You will use the Website solely for your personal and
                non-commercial use. Any use of this Website or its content other
                than for personal purposes is strictly prohibited.
              </li>
              <li>
                Investments made by you are from your verified bank account
                (primary holder’s bank account where such account is a joint
                account), from legitimate sources.
              </li>
            </ul>
          </div>
        </div>
        <div className="self-stretch flex flex-col items-start justify-start gap-[40px]">
          <p className="m-0 relative font-medium">14. User covenants:</p>
          <div className="m-0 self-stretch relative text-[inherit] leading-[30px] font-inherit">
            <ul className="m-0 list-decimal pl-[21px]">
              <li className="mb-0">
                When communicating with club100 through digital media, please:
              </li>
              <li className="mb-0">
                confirm you are visiting the authorized Website;
              </li>
              <li className="mb-0">
                Maintain confidentiality of your User ID and OTPs. club100’s
                Website is private, available only to Users through secure
                log-in procedures. Apart from allowing you to use your User ID
                and OTP to enter the Website, club100 or its representatives
                will never ask you for your User ID and/or OTP.
              </li>
              <li className="mb-0">
                Do not communicate or deal with personnel who are not affiliated
                with club100.
              </li>
              <li>
                Do not send emails to anyone with an address other than the
                authorized club100 e-mail addresses. club100 does not permit our
                employees and authorized representatives to send or receive work
                related emails from personal accounts or any other address.
              </li>
            </ul>
          </div>
        </div>
        <div className="self-stretch flex flex-col items-start justify-start gap-[40px]">
          <p className="m-0 relative font-medium">
            15. Effect on other agreements:
          </p>
          <p className="m-0 self-stretch relative leading-[30px]">
            Nothing contained in these User Terms is intended to modify or amend
            any other written agreement you may have with club100 or other Users
            of the Website ("Other Agreements") if any, that may currently be in
            effect. In the event of any inconsistency between these User Terms
            and any Other Agreements, the Other Agreements will govern. Some
            pages within the Website contain supplemental terms and conditions
            and additional disclosure and disclaimers, which are in addition to
            these User Terms. In the event of a conflict, the supplemental terms
            and conditions and additional disclosures and disclaimers will
            govern for those sections or pages.
          </p>
        </div>
        <div className="self-stretch flex flex-col items-start justify-start gap-[40px]">
          <p className="m-0 relative font-medium">16. Indemnity:</p>
          <p className="m-0 self-stretch relative leading-[30px]">
            You agree to indemnify and hold harmless club100 and (as applicable)
            its subsidiaries, affiliates, third-parties and their respective
            shareholders, officers, directors, agents, and employees, from any
            losses, liabilities, damages, costs and expenses, claims or demand,
            or actions including reasonable attorneys' fees asserted against or
            incurred by club100, made by any third party arising out of your
            breach or non-performance of terms of these User Terms, or the
            documents they incorporate by reference, or your violation of any
            law, rules or regulations or the rights of a third party.
          </p>
        </div>
        <div className="self-stretch flex flex-col items-start justify-start gap-[40px]">
          <p className="m-0 relative font-medium">
            17. Changes to these terms:
          </p>
          <p className="m-0 self-stretch relative leading-[30px]">
            We reserve the right to update (change, modify, add and/or delete)
            these User Terms from time to time, at our sole discretion, to
            reflect company initiatives, changes in the law or technology or
            changes in our practices. When we update these User Terms, we will
            intimate you of the amendments on your email address or on the
            Website. If you do not agree to the amendments, please do not use
            the Website any further. By continuing to use the Website, you will
            be deemed to have consented to the latest version of these User
            Terms.
          </p>
        </div>
        <div className="self-stretch flex flex-col items-start justify-start gap-[40px]">
          <p className="m-0 relative font-medium">18. Miscellaneous:</p>
          <div className="m-0 self-stretch relative text-[inherit] gap-4 leading-[30px] font-inherit">
            <ul className="m-0 list-decimal pl-[21px]">
              <li className="mb-0">General</li>
              <span className="block">
                None of the provisions of these User Terms will be deemed to
                constitute a partnership or agency between you and club100 and
                you will have no authority to bind club100 in any manner
                whatsoever.
              </span>
              <span className="block">&nbsp;</span>

              <li className="mb-0">
                Fiduciary Duty and Fairness of Charges (if any)
              </li>
              <span className="block pl-[30px] ">
                In providing you its Services, club100 will:
              </span>
              <ul className="m-0 list-disc pl-[34px]">
                <li className="mb-0">Put your best interests first;</li>
                <li className="mb-0">
                  Act with prudence, that is, with the skill, care, diligence
                  and good judgment of a professional;
                </li>
                <li className="mb-0">
                  Provide conspicuous, full and fair disclosure of all important
                  facts and not mislead you in any manner;
                </li>
                <li className="mb-0">Avoid conflicts of interest; and</li>
                <li className="mb-0">
                  Fully disclose and fairly manage, in your favor, any
                  unavoidable conflicts.
                </li>
              </ul>
              <span className="block">&nbsp;</span>

              <li className="mb-0">Notices</li>

              <span className="block">
                All notices and other communications required or permitted
                hereunder to be given to a party will be in writing, in the
                English language, and will be sent e-mail, or mailed by prepaid
                internationally-recognized courier or otherwise delivered by
                hand or by messenger, addressed to such party’s address as set
                forth below or at such other address as the party will have
                furnished to the other party in writing in accordance with this
                provision: If to club100: support@myclub100.com If to You: At
                the email address provided by You.
              </span>
              <span className="block">&nbsp;</span>
              <li className="mb-0">Severability</li>

              <span className="block">
                If any clause of these User Terms is deemed invalid, void or for
                any reason unenforceable, such clause will be severable and will
                not affect the validity and enforceability of the remaining
                clauses of these User Terms.
              </span>
              <span className="block">&nbsp;</span>
              <li className="mb-0">Entire agreement</li>
              <span className="block">
                These User Terms set forth the entire understanding and
                agreement between you and club100 with respect to the subject
                matter hereof.
              </span>
              <span className="block">&nbsp;</span>
              <li className="mb-0">Assignment</li>
              <span className="block">
                You cannot assign or otherwise transfer your rights or
                obligations under these User Terms to any third party. club100
                may transfer its rights and obligations (also known as "assign")
                under these User Terms without your prior express consent,
                provided that club100 will assign these User Terms on the same
                terms or terms that are no less advantageous to you.
              </span>
              <span className="block">&nbsp;</span>
              <li className="mb-0">Arbitration</li>

              <span className="block">{`If any dispute arises between you and club100 during your use of the Website or thereafter, in connection with the validity, interpretation, implementation or alleged breach of any provision of these User Terms, or the documents they incorporate by reference, the dispute will be referred to a sole Arbitrator who will be an independent and neutral third party identified by club100. The place of arbitration will be Mumbai, Gujarat. The arbitration proceedings will be in the English language and will be governed by Arbitration & Conciliation Act, 1996.`}</span>
              <span className="block">&nbsp;</span>
              <li className="mb-0">Governing Law</li>
              <span className="block">
                These User Terms or the documents they incorporate by reference
                will be governed and construed in accordance with the laws of
                India. Subject to clause of Arbitration above, all disputes
                arising under these User Terms between you and club100 will be
                subject to the exclusive jurisdiction of courts at Mumbai,
                Gujarat, India.
              </span>
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
};

export default TermsConditions;
